baseURL = "https://lukrene.github.io/freyer-translation/"
languageCode = "de-de"
title = "Christina Freyer"
theme = "initio"
relativeURLs = false
canonifyURLs = true



[params]
  banner = "img/header.jpg"
  author = "Christina Freyer"
  name = "Christina Freyer"
  description = "Konferenzdolmetschen, Übersetzen & Usability-Research aus einer Hand"
  showSubheader = true
  showServices = true
  showContact = true
  showAbout = true
  showfuerauftraggeber = true
  showLanguages = true
  showDownloads = false
  showRecentWorks = false
  DateForm = "January 2, 2006"
  about = "Konferenzdolmetschen"
  phone = "+49 151 75 00 6865"
  address = "Saportastraße 2, 80637 München"
  email = "info@freyer-translation.de"
  year = 2025
  avatar = "img/logo cf.png"
  avatarclass = "circle"
  logo = "img/logo cf.png"
  headerImage = "img/header.jpg"
  background = ""
  languages = "Deutsch ↔ Russisch ↔ Ukrainisch sowie Übersetzungen aus dem Englischen und Französischen"



[[menu.main]]
    name = "Home"
    url = "/freyer-translation/"
    weight = 1
[[menu.main]]
    name = "Konferenzdolmetschen & Übersetzen"
    url = "/freyer-translation/konferenzdolmetschen/"
    weight = 4
[[menu.main]]
    name = "Profil"
    url = "/freyer-translation/profil/"
    weight = 5
[[menu.main]]
    name = "Fachgebiete"
    url = "/freyer-translation/fachgebiete/"
    weight = 11
[[menu.main]]
    name = "Preise & Preisbildung"
    url = "/freyer-translation/preise-preisbildung/"
    weight = 14
[[menu.main]]
    name = "Referenzen"
    url = "/freyer-translation/referenzen/"
    weight = 16
[[menu.main]]
    name = "UX-Research"
    url = "/freyer-translation/ux-research/"
    weight = 20
[[menu.footer]]
    name = "Impressum"
    url = "/freyer-translation/impressum/"
    weight = 1

[[menu.footer]]
    name = "AGB"
    url = "/freyer-translation/agb/"
    weight = 2

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
        title = "linkedin"
        url = "https://www.linkedin.com/in/nickname"
    icon = "fab fa-linkedin-in"
    footer = true
    sharethis = true
    network = "linkedin"
